TA-1871 remove disability code validation
ministryofjustice/laa-cwa-feature-tests pull request #142
Opened 2022-11-17 09:40 UTC by solomonahmed

## What does this pull request do?

Please describe what you did.
New feature test to ensure disability code COG can be used after 1st April 2013.  It was previously being blocked by validation which is being removed.

I've also refactored some of the step definitions which create submission lines manually.  Minor mods as well to field/default yaml files to support features/refactoring.

## Why make these changes?

Please describe why the changes were needed.
The business have confirmed that the disability codes COG (& PHY/SEN - although these are not explicitly tested here) should be permitted for Crime and Civil submissions.

Refactoring work done to reduce tech debt and de-couple slightly the step definitions from the feature tests.

## Checklist

- [x] Provided link to a JIRA ticket: https://dsdmoj.atlassian.net/browse/TA-1871

2022-11-17 10:34 UTC, your requested changes
Awesome! 🤩
So excited to see developers proactively apply the DRY principle and reduce tech debt. 🎖️ 

I have to request changes only because I believe a few features need to be updated according to the changes (listed in the comments).

2022-11-17 10:34 UTC, your commented on features/step_definitions/cwa_outcome_steps.rb
> -When("user adds outcomes for Crime Lower Criminal Proceedings with fields like this:") do |table|
The features under `features/pricing/crime_lower/criminal_proceedings/` need to be updated accordingly

2022-11-17 10:34 UTC, your commented on features/step_definitions/cwa_outcome_steps.rb
> -When ('user adds an outcome for Immigration with {string}, {string}, {string}, {string}, {string}, {string} and {string}') \
This feature needs to be updated accordingly: `features/validations/legal_help/immigration_and_asylum/ecs_care_leaver_validations.feature`

2022-11-17 16:31 UTC, solomonahmed commented on features/step_definitions/cwa_outcome_steps.rb
> -When("user adds outcomes for Crime Lower Criminal Proceedings with fields like this:") do |table|
Done

2022-11-17 16:31 UTC, solomonahmed commented on features/step_definitions/cwa_outcome_steps.rb
> -When ('user adds an outcome for Immigration with {string}, {string}, {string}, {string}, {string}, {string} and {string}') \
Done

2022-11-18 10:15 UTC, your approved these changes
LGTM

2022-11-18 10:25 UTC, merged