Ta 2552
ministryofjustice/laa-cwa-feature-tests pull request #199
Opened 2024-03-06 09:06 UTC by JayVirdi

## What does this pull request do?

Please describe what you did.
Added feature tests to test the case start date error messages around the dates 01/10/2007 and 01/01/1995

## Why make these changes?

Please describe why the changes were needed.
To ensure that we had proper coverage to test incoming changes relating to TA-2556 and others

## Checklist

- [ ] Provided link to a JIRA ticket: https://dsdmoj.atlassian.net/browse/TA-2552

2024-03-08 08:55 UTC, solomonahmed requested changes

2024-03-08 08:55 UTC, solomonahmed commented on features/step_definitions/cwa_outcome_steps.rb
> +    if !outcome.has_key?("case_start_date") && !(area_of_law == "Crime Lower")
I'm unclear why this addition is needed?

2024-03-08 08:55 UTC, solomonahmed commented on features/validations/legal_help/immigration_and_asylum/case_start_date_validation.feature
> +  Scenario Outline: validate case start date for HOUSING
The feature file is called immigration_and_asylum but there are housing submissions in it?  Ideally if there is a need for a housing submission test then it needs to be in a legal_help/housing/case_start_date_validation.feature file.

2024-03-08 08:55 UTC, solomonahmed commented on run_failed_tests.sh
> +#!/bin/bash
What the purpose of this file?

2024-03-08 10:13 UTC, vimalsuresh commented on features/step_definitions/cwa_outcome_steps.rb
> +    if !outcome.has_key?("case_start_date") && !(area_of_law == "Crime Lower")
This was added as we had to test error messages in the code 
      Case Concluded Date is before Case Start Date
      Case Start Date is greater than today's date
To do this we had to manipulate the system date which would feed in tomorrows date in the case start date field. giving us this error. To do this we have to not pass "case_start_date" in the examples , but reliased crime lower case tests also do not pass case_start_date. so had to put this code to create exceptions.

2024-03-08 10:16 UTC, vimalsuresh commented on features/validations/legal_help/immigration_and_asylum/case_start_date_validation.feature
> +  Scenario Outline: validate case start date for HOUSING
I will move it to the respective folder. but the same would have to be done for asylum. Happy to move if , please let me know. I thought case_start_date validations would stay in one place. May me move it out of the categories folders.

2024-03-08 10:18 UTC, vimalsuresh commented on run_failed_tests.sh
> +#!/bin/bash
This shell file was created to make it easy to run failed tests in the kubernetes cluster. copy pasting the failed tests in to the shell script and running the shell would run the tests one by one.

2024-03-08 10:20 UTC, solomonahmed commented on features/step_definitions/cwa_outcome_steps.rb
> +    if !outcome.has_key?("case_start_date") && !(area_of_law == "Crime Lower")
Need to talk to you about this as I'm not sure about this approach.

2024-03-08 10:22 UTC, solomonahmed commented on features/validations/legal_help/immigration_and_asylum/case_start_date_validation.feature
> +  Scenario Outline: validate case start date for HOUSING
Let's have a chat.  I take your point re: Immigration And Asylum.  I think the naming conventions need to be consistent and logical.  If there are **Immigration** codes in the this file then they need to be in an **Immigration** folder.  Certainly, Housing tests need to be in a housing directory.

2024-03-18 09:50 UTC, vimalsuresh commented on features/step_definitions/cwa_outcome_steps.rb
> +    if !outcome.has_key?("case_start_date") && !(area_of_law == "Crime Lower")
issue created to look at refactor
https://github.com/ministryofjustice/laa-cwa-feature-tests/issues/202

2024-03-18 09:51 UTC, vimalsuresh commented on run_failed_tests.sh
> +#!/bin/bash
the shell has been deleted

2024-03-18 09:51 UTC, vimalsuresh commented on features/validations/legal_help/immigration_and_asylum/case_start_date_validation.feature
> +  Scenario Outline: validate case start date for HOUSING
Housing tests are now moved to housing section

2024-03-19 10:13 UTC, JayVirdi commented
Test changes made and approved, issue raised for refactor. Merging.

2024-03-19 10:13 UTC, merged