TA-2894
ministryofjustice/laa-cwa-feature-tests pull request #235
Opened 2024-10-08 08:41 UTC by JayVirdi

## What does this pull request do?

Please describe what you did.
Added feature tests for YOUF, YOUK, and YOUL.

## Why make these changes?

Please describe why the changes were needed.
To ensure that we have adequate test coverage.

## Checklist

- [ ] Provided link to a JIRA ticket: https://dsdmoj.atlassian.net/browse/TA-2984

2024-10-08 10:45 UTC, vimalsuresh commented on features/validations/crime_lower/youe_validations.feature
> +Feature: YOUE code Bulk load validations
this test has both bulkload and manaul validation, can you amend the feature name please

2024-10-08 10:45 UTC, vimalsuresh commented on features/validations/crime_lower/youf_validations.feature
> +Feature: YOUF code Bulk load validations
same as above

2024-10-08 10:45 UTC, vimalsuresh commented on features/validations/crime_lower/youk_validations.feature
> +Feature: YOUK code Bulk load validations
same as above

2024-10-08 10:45 UTC, vimalsuresh commented on features/validations/crime_lower/youl_validations.feature
> +Feature: YOUL code Bulk load validations
same as above

2024-10-08 11:09 UTC, JayVirdi commented on features/validations/crime_lower/youl_validations.feature
> +Feature: YOUL code Bulk load validations
I have pushed a change to fix these. Please re-review.

2024-10-08 11:26 UTC, solomonahmed commented on features/validations/crime_lower/youe_validations.feature
> +Feature: YOUE code Bulk load validations
Ideally these are either in separate tests or tagged appropriately.

2024-10-08 11:28 UTC, solomonahmed commented on features/support/am/defaults/am_crime_lower_defaults.yml
> +youth_court_base: &youth_court_base
Are the Youth Court codes within a separate category of law within Crime Lower?

2024-10-08 11:36 UTC, solomonahmed requested changes

2024-10-08 11:36 UTC, solomonahmed commented on features/support/am/fields/am_crime_lower.yml
> +    YOUE:
These codes will need to sit under criminal proceedings.  But, I will check with Janet on this.

2024-10-08 11:40 UTC, solomonahmed commented on features/validations/crime_lower/youe_validations.feature
> +Feature: YOUE code Bulk load validations
Also, I wondered if we could start organising the tests into a folder structure which matches the categories of law within Crime Lower?  So youth court validation will sit in crime_lower/criminal_proceedings/youe_validations.feature.

2024-10-09 11:35 UTC, JayVirdi commented on features/validations/crime_lower/youe_validations.feature
> +Feature: YOUE code Bulk load validations
I have made the changes as requested, please re-review

2024-10-10 14:06 UTC, solomonahmed approved these changes
Great stuff @JayVirdi .

2024-10-10 14:27 UTC, merged